name: Build ARM Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build 
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: newapp:latest
          platforms: linux/arm64
          outputs: type=tar,dest=newapp.tar
    
      - shell: bash
        run: |
            zstd newapp.tar -o newapp.tzst

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: newapp
          path: newapp.tzst