name: Build ARM Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build 
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: myapp:latest
          platforms: linux/arm/v7

      - shell: bash
        run: |
            docker save -o myapp.tar myapp:latest
            zstd us_container.tar -o myapp_image.tzst

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp_image
          path: us_container